import type { CliIntrospection } from "@relay/contracts";
import { marker, type GeneratedFile, type Generator } from "./types.js";

/**
 * CLI reference — generated from `fixtures/cli-introspection.json`
 * (T2_CLI): the single Mintlify page `docs-mintlify/cli-reference.mdx`
 * plus one page per top-level command under `cli-docs/`, and the
 * `cli-docs/README.md` index. Commands, flags, defaults, usage, examples,
 * and the contractual exit codes — all from the capture, nothing
 * hand-authored.
 */

type Command = CliIntrospection["commands"][number];

const MD_MARKER =
  "<!-- GENERATED BY CONCORD — do not edit. Source: fixtures/cli-introspection.json (T2_CLI). -->";

function flagsTable(command: Command): string {
  if (command.flags.length === 0) return "";
  const rows = command.flags.map(
    (flag) =>
      `| \`${flag.name}\` | ${flag.type} | ${flag.required ? "yes" : "no"} | ${
        flag.default === null ? "—" : `\`${JSON.stringify(flag.default)}\``
      } | ${flag.description} |`,
  );
  return `\n| flag | type | required | default | description |\n|---|---|---|---|---|\n${rows.join("\n")}\n`;
}

function commandSection(command: Command, headingLevel: string): string {
  const examples =
    command.examples.length > 0
      ? `\nExamples:\n\n${command.examples.map((e) => `\`\`\`\n$ ${e}\n\`\`\``).join("\n")}\n`
      : "";
  return `${headingLevel} ${command.path}

${command.summary}.

\`\`\`
${command.usage.trimEnd()}
\`\`\`
${flagsTable(command)}${examples}`;
}

function exitCodesTable(cli: CliIntrospection): string {
  const root = cli.commands[0] as Command;
  const rows = root.exit_codes.map((e) => `| \`${e.code}\` | ${e.meaning} |`);
  return `| code | meaning |\n|---|---|\n${rows.join("\n")}`;
}

/** Top-level grouping: `projects list` belongs to the `projects` page. */
function topOf(command: Command): string {
  const first = command.path.split(" ")[0] as string;
  return first === "relay" ? "relay" : first;
}

export const cliReferenceGenerator: Generator = {
  id: "cli-reference",
  generate(_facts, inputs) {
    const cli = inputs.cli;
    const files: GeneratedFile[] = [];

    // 1) The single Mintlify reference page.
    const sections = cli.commands.map((c) => commandSection(c, "##"));
    files.push({
      path: "docs-mintlify/cli-reference.mdx",
      content: `---
title: "CLI reference"
description: "Generated reference for every relay command, flag, and exit code."
owner: "concord"
generated: true
---

${marker("cli.command.<command_path>.{flags,summary} (T2_CLI)")}

Generated from \`relay introspect --json\` (CLI v${cli.cli_version}).

## Exit codes

${exitCodesTable(cli)}

${sections.join("\n\n")}
`,
    });

    // 2) One page per top-level command under cli-docs/.
    const groups = new Map<string, Command[]>();
    for (const command of cli.commands) {
      const top = topOf(command);
      groups.set(top, [...(groups.get(top) ?? []), command]);
    }
    for (const [top, commands] of groups) {
      const body = commands.map((c) => commandSection(c, "##")).join("\n\n");
      files.push({
        path: `cli-docs/${top}.md`,
        content: `${MD_MARKER}\n# ${top === "relay" ? "relay (root command)" : `relay ${top}`}\n\n${body}\n`,
      });
    }

    // 3) The index.
    const index = [...groups.keys()]
      .map((top) => `- [${top}](./${top}.md)`)
      .join("\n");
    files.push({
      path: "cli-docs/README.md",
      content: `${MD_MARKER}\n# relay CLI reference (generated)\n\nGenerated from \`relay introspect --json\` (CLI v${cli.cli_version}). One page\nper top-level command; nothing in this directory is hand-authored.\n\n${index}\n`,
    });
    return files;
  },
};
