import type { Generator } from "./types.js";

/**
 * Structured metadata fragment referenced from navigation.json via `$ref`
 * (`generated/navigation.json`): the navigation group for generated pages.
 * JSON cannot carry an MDX comment; the marker rides in a `_concord` field
 * (Mintlify ignores unknown keys).
 */
export const navigationGenerator: Generator = {
  id: "navigation-fragment",
  generate() {
    const fragment = {
      _concord: "GENERATED BY CONCORD — do not edit. Source: generated page inventory.",
      group: "Changes",
      pages: ["changelog"],
    };
    return [
      {
        path: "docs-mintlify/generated/navigation.json",
        content: `${JSON.stringify(fragment, null, 2)}\n`,
      },
    ];
  },
};
