import type { CliIntrospection, FactClaim } from "@relay/contracts";

/**
 * Deterministic generators (contracts.md §13): pure and idempotent —
 * `generate(facts, inputs)` returns the COMPLETE intended content of every
 * file the generator owns. A test runs each twice and asserts byte
 * equality (invariant I8). Diffing against the estate and hand-edit
 * detection live in the runner, not in generators.
 */

export interface GeneratorInputs {
  /** `relay introspect --json` capture (fixtures/cli-introspection.json). */
  cli: CliIntrospection;
  /** Current estate files — read-only context (description patching). */
  files: ReadonlyArray<{ path: string; content: string }>;
}

export interface GeneratedFile {
  /** Estate-relative path — never the `estate/` mount prefix (I15). */
  path: string;
  content: string;
}

export interface Generator {
  id: string;
  generate(facts: readonly FactClaim[], inputs: GeneratorInputs): GeneratedFile[];
}

export function factValue(facts: readonly FactClaim[], key: string): unknown {
  return facts.find((f) => f.key === key)?.value;
}

export function marker(sourceFacts: string): string {
  return `{/* GENERATED BY CONCORD — do not edit. Source facts: ${sourceFacts} */}`;
}
