// Phase 13 — invariant I8: every generator produces byte-identical output
// across two runs; the runner never emits llms.txt (G7); hand-edit
// detection overwrites AND warns (documented behavior).
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { CliIntrospectionSchema, type FactClaim } from "@relay/contracts";
import { GENERATORS, generateAll, runGenerators } from "../src/generators/index.js";
import type { GeneratorInputs } from "../src/generators/types.js";
import { readEstate } from "../cli/ingest.js";
import { generatorFacts } from "../cli/generator-facts.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const CLI = CliIntrospectionSchema.parse(
  JSON.parse(readFileSync(join(root, "fixtures", "cli-introspection.json"), "utf8")),
);
const FACTS: FactClaim[] = generatorFacts();

function inputs(): GeneratorInputs {
  return { cli: CLI, files: readEstate() };
}

describe("generators (I8: idempotent, pure)", () => {
  it("every generator produces byte-identical output across two runs", () => {
    for (const generator of GENERATORS) {
      const one = generator.generate(FACTS, inputs());
      const two = generator.generate(FACTS, inputs());
      expect(JSON.stringify(two), generator.id).toBe(JSON.stringify(one));
      expect(one.length, generator.id).toBeGreaterThan(0);
    }
  });

  it("generated files carry the CONCORD marker header", () => {
    for (const file of generateAll(FACTS, inputs())) {
      if (file.path.endsWith(".json")) {
        expect(file.content, file.path).toContain("GENERATED BY CONCORD");
      } else if (!file.path.includes("supported-files")) {
        // description-only outputs patch hand-authored pages — no marker
        expect(file.content, file.path).toContain("GENERATED BY CONCORD — do not edit");
      }
    }
  });

  it("no generator ever emits llms.txt or llms-full.txt (G7)", () => {
    const paths = generateAll(FACTS, inputs()).map((f) => f.path);
    for (const path of paths) {
      expect(path).not.toMatch(/llms(-full)?\.txt$/);
    }
    // And the guard is mechanical, not conventional:
    const evil = {
      id: "evil",
      generate: () => [{ path: "docs-mintlify/llms.txt", content: "x" }],
    };
    const originalGenerate = GENERATORS[0]!.generate;
    try {
      (GENERATORS[0] as { generate: typeof originalGenerate }).generate = evil.generate;
      expect(() => generateAll(FACTS, inputs())).toThrow(/G7/);
    } finally {
      (GENERATORS[0] as { generate: typeof originalGenerate }).generate = originalGenerate;
    }
  });

  it("the committed estate matches generator output exactly (no drift, no warnings)", () => {
    const { diffs, warnings } = runGenerators(FACTS, FACTS, inputs());
    expect(warnings).toEqual([]);
    expect(diffs.map((d) => d.path)).toEqual([]);
  });

  it("hand-editing a generated file yields the warning AND an overwrite", () => {
    const files = readEstate().map((f) =>
      f.path === "docs-mintlify/generated/availability-matrix.mdx"
        ? { ...f, content: f.content.replace("## Limits", "## Limits (edited by hand)") }
        : f,
    );
    const { diffs, warnings } = runGenerators(FACTS, FACTS, { cli: CLI, files });
    expect(warnings.length).toBe(1);
    expect(warnings[0]).toMatchObject({
      kind: "generated_file_hand_edited",
      path: "docs-mintlify/generated/availability-matrix.mdx",
    });
    const overwrite = diffs.find((d) => d.path === "docs-mintlify/generated/availability-matrix.mdx");
    expect(overwrite).toBeDefined();
    expect(overwrite!.after).toContain("## Limits");
    expect(overwrite!.after).not.toContain("edited by hand");
  });

  it("a generator rewrite and a span substitution to ONE file compose into one patch", async () => {
    const { runPipeline } = await import("../src/pipeline.js");
    const snapshot = (facts: FactClaim[]) => ({
      snapshot_id: "snap",
      generated_at: "2026-07-26T00:00:00.000Z",
      relay_contracts_version: "1.0.0",
      facts,
    });
    const current = FACTS.map((f) =>
      f.key === "limit.upload.csv.max_bytes" ? { ...f, value: 26_214_400 } : f,
    );
    const out = runPipeline({
      previous: snapshot(FACTS),
      current: snapshot(current),
      files: readEstate(),
      detectedAt: "2026-07-26T00:00:00.000Z",
      cli: CLI,
    });
    const patch = out.patches.find((p) => p.path === "docs-mintlify/supported-files.mdx");
    expect(patch).toBeDefined();
    // BOTH the generated description and the mechanical body substitution:
    expect(patch!.after).toContain('the 25 MB size limit');
    expect(patch!.after).toContain("Maximum file size: 25 MB.");
    expect(patch!.after).not.toContain("10 MB");
  });

  it("a fact-driven regen is NOT a hand-edit warning", () => {
    const previous = FACTS;
    const current = FACTS.map((f) =>
      f.key === "plan.feature.connector_drive.min_plan" ? { ...f, value: "pro" } : f,
    );
    const { diffs, warnings } = runGenerators(previous, current, inputs());
    expect(warnings).toEqual([]);
    const regen = diffs.find((d) => d.path === "docs-mintlify/generated/plan-gating.mdx");
    expect(regen).toBeDefined();
    expect(regen!.after).toContain("| connector_drive | pro |");
  });
});
