// Generates src/estate.generated.ts — the WHOLE estate inlined at build
// time through the repo-1 submodule mount, with ESTATE-RELATIVE paths (the
// `estate/` mount prefix never reaches an id — invariant I15). Windows-
// friendly (G19): plain node, forward-slash normalization.
import { readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ESTATE = join(here, "..", "..", "..", "estate");
const OUT = join(here, "..", "src", "estate.generated.ts");

const INCLUDE = /\.(mdx?|json)$/;
const files = [];
const walk = (dir) => {
  for (const name of readdirSync(dir)) {
    if (name === ".git" || name === "node_modules") continue;
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full);
    else if (INCLUDE.test(name)) {
      files.push({
        path: relative(ESTATE, full).replaceAll("\\", "/"),
        content: readFileSync(full, "utf8"),
      });
    }
  }
};
walk(ESTATE);
files.sort((a, b) => (a.path < b.path ? -1 : 1));

const body = files
  .map((f) => `  { path: ${JSON.stringify(f.path)}, content: ${JSON.stringify(f.content)} },`)
  .join("\n");

// The estate commit the build was baked from — the publish branch base
// (Phase 19). Must be a commit that exists on the estate remote.
const estateSha = execFileSync("git", ["-C", ESTATE, "rev-parse", "HEAD"], {
  encoding: "utf8",
}).trim();

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `// GENERATED by scripts/generate-estate.mjs — do not edit. Regenerated on build.\n` +
    `export const ESTATE_SHA = ${JSON.stringify(estateSha)};\n` +
    `export const ESTATE_FILES: ReadonlyArray<{ path: string; content: string }> = [\n${body}\n];\n`,
  "utf8",
);
console.log(`estate.generated.ts: ${files.length} files @ ${estateSha.slice(0, 7)}`);
