// Generates src/runs.generated.ts from fixtures/runs/*.json — the committed
// ChangeLabRun recordings served by the replay endpoint. Recordings are
// REAL runs captured verbatim (Phase 17); nothing here is hand-authored.
import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const RUNS = join(here, "..", "..", "..", "fixtures", "runs");
const OUT = join(here, "..", "src", "runs.generated.ts");

const entries = [];
if (existsSync(RUNS)) {
  for (const name of readdirSync(RUNS).sort()) {
    if (!name.endsWith(".json")) continue;
    const content = JSON.parse(readFileSync(join(RUNS, name), "utf8"));
    entries.push({ scenario: name.replace(/\.json$/, ""), run: content });
  }
}
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `// GENERATED by scripts/generate-runs.mjs — do not edit.\n` +
    `export const REPLAY_RUNS: ReadonlyArray<{ scenario: string; run: unknown }> = ${JSON.stringify(entries, null, 1)};\n`,
  "utf8",
);
console.log(`runs.generated.ts: ${entries.length} recordings`);
